### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2022_NutriTracker#2]
Instead of uploading an APK directly to the repository, a stable release should be added to the releases page: https://github.com/matf-pp/2022_NutriTracker/releases/new

**Comment by Marko590** [comment]
Closed issue by adding a stable release to the release page.

**Comment by ivan-ristovic** [comment]
The [APK file](https://github.com/matf-pp/2022_NutriTracker/blob/main/nutritracker.apk) can now be removed from the repository.
